joint_limits: 
  r1_shoulder_pan_joint: 
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    max_position: 6.283
    max_velocity: 3.141
    min_position: -6.283
  r1_shoulder_lift_joint: 
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    max_position: 6.283
    max_velocity: 3.141
    min_position: -6.283
  r1_elbow_joint: 
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 3.141
    max_velocity: 3.141
    min_position: -3.141
  r1_wrist_1_joint: 
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 12.0
    max_position: 6.283
    max_velocity: 6.283
    min_position: -6.283
  r1_wrist_2_joint: 
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 12.0
    max_position: 6.283
    max_velocity: 6.283
    min_position: -6.283
  r1_wrist_3_joint: 
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 12.0
    max_position: 6.283
    max_velocity: 6.283
    min_position: -6.283
  r2_shoulder_pan_joint: 
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    max_position: 6.283
    max_velocity: 3.141
    min_position: -6.283
  r2_shoulder_lift_joint: 
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    max_position: 6.283
    max_velocity: 3.141
    min_position: -6.283
  r2_elbow_joint: 
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 3.141
    max_velocity: 3.141
    min_position: -3.141
  r2_wrist_1_joint: 
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 12.0
    max_position: 6.283
    max_velocity: 6.283
    min_position: -6.283
  r2_wrist_2_joint: 
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 12.0
    max_position: 6.283
    max_velocity: 6.283
    min_position: -6.283
  r2_wrist_3_joint: 
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 12.0
    max_position: 6.283
    max_velocity: 6.283
    min_position: -6.283