joint_limits: 
  r1_shoulder_pan_joint: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 6.3355
    max_velocity: 18.0
    min_position: -6.3355
  r1_shoulder_lift_joint: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 6.3355
    max_velocity: 18.0
    min_position: -6.3355
  r1_elbow_joint: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 6.3355
    max_velocity: 18.0
    min_position: -6.3355
  r1_wrist_1_joint: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 6.3355
    max_velocity: 18.0
    min_position: -6.3355
  r1_wrist_2_joint: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 6.3355
    max_velocity: 18.0
    min_position: -6.3355
  r1_wrist_3_joint: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 6.3355
    max_velocity: 18.0
    min_position: -6.3355
  r2_shoulder_pan_joint: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 6.3355
    max_velocity: 18.0
    min_position: -6.3355
  r2_shoulder_lift_joint: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 6.3355
    max_velocity: 18.0
    min_position: -6.3355
  r2_elbow_joint: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 6.3355
    max_velocity: 18.0
    min_position: -6.3355
  r2_wrist_1_joint: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 6.3355
    max_velocity: 18.0
    min_position: -6.3355
  r2_wrist_2_joint: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 6.3355
    max_velocity: 18.0
    min_position: -6.3355
  r2_wrist_3_joint: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 6.3355
    max_velocity: 18.0
    min_position: -6.3355