joint_limits: 
  r1_joint_1: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 2.87
    max_velocity: 2.0
    min_position: -2.87
  r1_joint_2: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 1.91
    max_velocity: 2.0
    min_position: -1.91
  r1_joint_3: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 1.22
    max_velocity: 2.0
    min_position: -1.91
  r1_joint_4: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 2.79
    max_velocity: 2.0
    min_position: -2.79
  r1_joint_5: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 2.09
    max_velocity: 2.0
    min_position: -2.09
  r1_joint_6: 
    has_acceleration_limits: True
    has_effort_limits: True
    has_position_limits: True
    has_velocity_limits: True
    max_acceleration: 3.0
    max_effort: 150.0
    max_position: 6.98
    max_velocity: 2.0
    min_position: -6.98